recruiter-front-end/src/App.js
recruiter-front-end/src/components/Login.js
recruiter-front-end/src/components/NewCandidate/NewCandidate.js

Pair programed with @vud531 
- Created route and Link to /new-candidate
- Created /components/NewCandidate

Create form inputs to add new candidate

---

recruiter-front-end/src/App.css
recruiter-front-end/src/App.js
recruiter-front-end/src/components/Contacts/Contacts.js

- Import Menu and Menu.Item from Semantic UI into App.js and add Link to /contacts
- Create Contacts component using Semantic UI for that sets compoent state to the form inputs and sends the email and name as a POST request to a [hardcoded endpoint](https://recruiter-back-end.herokuapp.com/users/1/contacts)

Create Semantic UI form to add a new contact hard coded to user1

---

recruiter-front-end/src/components/Mailer/index.js

changed localhost:4000 to dynamic url -- fixed cors errors

---

recruiter-front-end/src/App.js
recruiter-front-end/src/actions/index.js
recruiter-front-end/src/components/Contacts/Contacts.js
recruiter-front-end/src/components/Dashboard/index.js
recruiter-front-end/src/components/Login.js
recruiter-front-end/src/components/Mailer/index.js
recruiter-front-end/src/components/NewCandidate/NewCandidate.js
recruiter-front-end/src/components/User/index.js
recruiter-front-end/src/components/Users/index.js

Updated New Candidate Form to successfully post to back end API. A user will need the ability to input the data for a candidate so that the rule engine can send the candidate to the correct person or team.

Updated New Candidate Form to successfully post to back end API

---

recruiter-front-end/.eslintignore
recruiter-front-end/.eslintrc.json
recruiter-front-end/.prettierrc.json
recruiter-front-end/.vscode/settings.json
recruiter-front-end/package.json
recruiter-front-end/settings.json
recruiter-front-end/src/App.js
recruiter-front-end/src/actions/index.js
recruiter-front-end/src/components/Contacts/Contacts.js
recruiter-front-end/src/components/Dashboard/index.js
recruiter-front-end/src/components/Mailer/index.js
recruiter-front-end/src/components/NewCandidate/NewCandidate.js
recruiter-front-end/src/components/RuleView/CreateCondition.js
recruiter-front-end/src/components/RuleView/HelpModal.js
recruiter-front-end/src/components/RuleView/MainHeader.js
recruiter-front-end/src/components/RuleView/RuleMain.js
recruiter-front-end/src/components/User/index.js
recruiter-front-end/src/components/Users/index.js
recruiter-front-end/src/config/fire.js
recruiter-front-end/src/helpers/history.js
recruiter-front-end/src/index.js
recruiter-front-end/src/reducers/index.js
recruiter-front-end/src/serviceWorker.js
recruiter-front-end/yarn.lock

Added style rules and prettier/eslint config to prevent merge conflicts originating from style mismatching.
Prevents future merge conflicts originating from style mismatching of editors.

added prettier config matching airbnb rules. same setup as backend

---

recruiter-front-end/src/components/NewCandidate/NewCandidate.js

Added LinkedIn exist checkbox with field for url if enabled

---

recruiter-front-end/.env
recruiter-front-end/src/components/Login.js

When a user signed in, it was not adding them to the database. That is fixed now.

Fixed user post to database problem

---

recruiter-front-end/src/App.js
recruiter-front-end/src/components/Users/index.js
recruiter-front-end/src/views/NewContactGroup/NewContactGroup.js
recruiter-front-end/src/views/NewUserLandingPage/NewUserLandingPage.js

**User Story 1:** When a user signs up for the first time they are asked to "Add a Contact Group" which goes to another page asking them to enter in the name of that contact group.
**User Story 2:** When a user clicks, "What is a contact group?", a modal will appear that explain what a contact group is and how they can add multiple contacts to a contacr group

Completed New User Sign Up - Step 2

---

recruiter-front-end/src/App.js
recruiter-front-end/src/views/NewRulesPage/Education.js
recruiter-front-end/src/views/NewRulesPage/Skills.js

**User Story 1:** When a user clicks "What is a rule?" a modal will pop up explaining what rules are and running through an email rule of if a candidate has less a bachelors degree and less than 3 years of experience they will be sent to a manager contact group if they create another group called directors and create a rule for candidates with a MBA and at least 3 years of experience then they will be sent to the directors group (Step 4)
**User Story 2: ** When a user clicks, "I'm Confused. Please explain how this will work", a modal will appear that explains the mechanics of the rule engine. (Step 5)
**User Story 3: ** When a user clicks "Next" on the education tab page they will see a form that says skills. The skills option in the menu will have a different background color or …

Create Views For Education and Skill Rules

---

recruiter-front-end/package.json
recruiter-front-end/src/App.js
recruiter-front-end/src/views/AddCandidatePage/AddCandidatePage.js
recruiter-front-end/yarn.lock

Add Candidate View ( Still working on functionality and other issues )

---

recruiter-front-end/src/App.js
recruiter-front-end/src/views/NewRulesPage/Education.js
recruiter-front-end/src/views/NewRulesPage/Experience.js
recruiter-front-end/src/views/NewRulesPage/Skills.js

Manually tested and confirmed that the form correctly logs the form inputs and routes to the correct page with the corresponding view component.

Create View for Experience Rule 

---

recruiter-front-end/src/components/DegreeDropdown/DegreeDropdown.js
recruiter-front-end/src/components/ExperienceDropdown/ExperienceDropdown.js
recruiter-front-end/src/components/MajorDropdown/MajorDropdown.js
recruiter-front-end/src/views/AddCandidatePage/AddCandidatePage.js

Cleaned up the code for AddCandidatePage.js

---

recruiter-front-end/src/components/Contacts/Contacts.js
recruiter-front-end/src/components/Contacts/NewContactForm.js
recruiter-front-end/src/components/Login.js
recruiter-front-end/src/components/NewCandidate/NewCandidate.js
recruiter-front-end/src/components/NewGroup/CreateGroupForm.js
recruiter-front-end/src/components/NewGroup/EditGroupForm.js
recruiter-front-end/src/views/NewRulesPage/Education.js
recruiter-front-end/src/views/NewRulesPage/Experience.js
recruiter-front-end/src/views/NewRulesPage/Skills.js

Added token headers to all axios requests.

---

recruiter-front-end/src/App.js
recruiter-front-end/src/components/Contacts/Contacts.js
recruiter-front-end/src/views/NewContactGroup/ContactGroup.js
recruiter-front-end/src/views/NewContactGroup/Contacts.js
recruiter-front-end/src/views/NewRulesPage/Education.js
recruiter-front-end/src/views/NewRulesPage/Experience.js
recruiter-front-end/src/views/NewRulesPage/Skills.js

- Add fail tab to Step Group component in ContactGroup, Contacts, Education, Experience and Skills. 
- Add back button in each step and updated button styles

Add new tab in stepper navigation and added back buttons

---

recruiter-front-end/src/components/Checkout/Checkout.js

I accidentally pushed localhost:4000 to master instead of the correct endpoint for the backend, so Stripe is broken. 
- [ X] Bug fix (non-breaking change which fixes an issue)
- [ X] Complete, tested, ready to review and merge

changed localhost to the correct endpoint

---

recruiter-front-end/src/App.js
recruiter-front-end/src/actions/engineActions.js
recruiter-front-end/src/actions/ruleActions.js
recruiter-front-end/src/components/Engines/EngineCard.js
recruiter-front-end/src/components/Engines/EngineCardRules.js
recruiter-front-end/src/components/Engines/EngineDash.js
recruiter-front-end/src/components/Engines/engine.css
recruiter-front-end/src/views/NewUserLandingPage/NewUserLandingPage.js

Engine dashboard view (contains viewpoint for engines and rules).
Delete+add buttons (delete rule working 100%).
Edit placeholder. Still needs functions.
Cannot continue any further until building the formatter. Moving onto that right now.

engine dashboard

---

recruiter-front-end/src/App.js
recruiter-front-end/src/components/NewCandidate/NewCandidate.js
recruiter-front-end/src/views/AddCandidatePage/AddCandidatePage.js
recruiter-front-end/src/views/AddCandidatePage/CandidateExperience.js

adding form

---

recruiter-front-end/src/App.js
recruiter-front-end/src/MarketingPage.js
recruiter-front-end/src/components/Cards/MarketingCards.js
recruiter-front-end/src/components/Login.js
recruiter-front-end/src/components/MarketingPage.js
recruiter-front-end/src/views/AddCandidatePage/CandidateEngine.js
recruiter-front-end/src/views/NewUserLandingPage/NewUserLandingPage.js

This adds the marketing page (with some cleaned up language) to the part of the app that users who aren't logged in can see. 

Added marketing page so that users who aren't logged in can see it

---

recruiter-front-end/src/App.js
recruiter-front-end/src/views/AddCandidatePage/CandidateExperience.js

candidate and rules array lineup

---

recruiter-front-end/src/App.js
recruiter-front-end/src/components/Engines/EngineDash.js
recruiter-front-end/src/views/NewRulesPage/Confirmation.js
recruiter-front-end/src/views/NewRulesPage/Education.js

Update new engine button, add fallback to App.js and modal to prevent blank fallbackEmail

---

recruiter-front-end/src/App.js
recruiter-front-end/src/actions/ruleActions.js
recruiter-front-end/src/components/Cards/MarketingCards.js
recruiter-front-end/src/components/Contacts/SpecificContact/ExampleContact.js
recruiter-front-end/src/components/Engines/EngineCard.js
recruiter-front-end/src/components/Engines/EngineCardRules.js
recruiter-front-end/src/views/NewRulesPage/Confirmation.js
recruiter-front-end/src/views/NewRulesPage/Education.js
recruiter-front-end/src/views/NewRulesPage/Experience.js
recruiter-front-end/src/views/NewRulesPage/NewRuleContacts.js

Added delete an engine functionality. 
Fixed bug where url doesn't reset on logout. 
Changed add contact in engine flow so it actually adds contacts to contacts table and lets users select contacts from drop down. 
Comments out app this.state button. 

contacts update and bug fixes

---

recruiter-front-end/src/App.js
recruiter-front-end/src/views/NewRulesPage/Confirmation.js
recruiter-front-end/src/views/NewRulesPage/Education.js
recruiter-front-end/src/views/NewRulesPage/Experience.js
recruiter-front-end/src/views/NewRulesPage/NewEngine.js
recruiter-front-end/src/views/NewRulesPage/NewRuleContacts.js
recruiter-front-end/src/views/NewRulesPage/Skills.js

updated contacts to an array of emails and changed "contacts" to "my contacts" or "rule contacts" depending on where it is. 

updated contacts to an array of emails

---

recruiter-front-end/src/views/NewRulesPage/NewEngine.js

Fixed tokenHeader error in post to engines axios call

post to engines is working now

---

recruiter-front-end/src/App.js
recruiter-front-end/src/components/Cards/MarketingCards.js
recruiter-front-end/src/components/Contacts/NewContactForm.js
recruiter-front-end/src/views/NewRulesPage/Confirmation.js
recruiter-front-end/src/views/NewRulesPage/Education.js
recruiter-front-end/src/views/NewRulesPage/Experience.js
recruiter-front-end/src/views/NewRulesPage/NewRuleContacts.js
recruiter-front-end/src/views/NewRulesPage/Skills.js
recruiter-front-end/src/views/NewUserLandingPage/NewUserLandingPage.js

Mobile and Responsive Styles for Navbar and Marketing Cards

Mobile and Responsive Styles for Navbar and Marketing Cards

---

recruiter-front-end/src/App.js
recruiter-front-end/src/components/Engines/EngineCard.js
recruiter-front-end/src/views/AddCandidatePage/CandidateSend.js
recruiter-front-end/src/views/NewRulesPage/Confirmation.js
recruiter-front-end/src/views/NewRulesPage/EngineCreationSuccess.js
recruiter-front-end/src/views/NewRulesPage/NewEngine.js

Fixed token error non-issue that became an issue. Created a fallbackEmail and fallbackName put request to add them to the engine and created a way to confirm to the user that that happened (the send candidate through an engine function on the frontend should work once the backend PR I made is also merged-- the fallback part will also work). Fixed back button that went too far on rules creation flow. Routed the rules creation submission to the engines router after it is completed.
Everything in this checklist is required for each PR.  Please do not approve a PR …

Fixed auth bug, created fallback creation function and confirmation, fixed some routing issues

---

recruiter-front-end/src/App.js
recruiter-front-end/src/components/Contacts/Contacts.js
recruiter-front-end/src/components/Engines/EngineDash.js
recruiter-front-end/src/views/AddCandidatePage/CandidateEducation.js
recruiter-front-end/src/views/NewRulesPage/Confirmation.js
recruiter-front-end/src/views/NewRulesPage/Education.js
recruiter-front-end/src/views/NewRulesPage/Experience.js
recruiter-front-end/src/views/NewRulesPage/NewEngine.js
recruiter-front-end/src/views/NewRulesPage/NewRuleContacts.js
recruiter-front-end/src/views/NewUserLandingPage/NewUserLandingPage.js

Multiple Rule Engine in App.js state and confirmation screen

Multiple Rule Engine in App.js state and confirmation screen

---

recruiter-front-end/src/App.js
recruiter-front-end/src/actions/ruleActions.js
recruiter-front-end/src/components/Engines/EngineCard.js
recruiter-front-end/src/components/Engines/EngineCardRules.js

Implemented new engine dashboard styles and creation+storing of non-parsed version of rule onto the backend, which is then read by engine dashboard for conditionally rendering rules set on the engine.

Non-Parse & Engine Dashboard

---

recruiter-front-end/.vscode/settings.json
recruiter-front-end/package.json
recruiter-front-end/public/_redirects
recruiter-front-end/src/App.js
recruiter-front-end/src/actions/contactActions.js
recruiter-front-end/src/actions/emailActions.js
recruiter-front-end/src/actions/engineActions.js
recruiter-front-end/src/actions/groupActions.js
recruiter-front-end/src/actions/groupContactsActions.js
recruiter-front-end/src/actions/ruleActions.js
recruiter-front-end/src/actions/userActions.js
recruiter-front-end/src/components/Engines/AddRuleToEngine/AddRuleToEngine.js
recruiter-front-end/src/components/Engines/AddRuleToEngine/NewRuleContact.js
recruiter-front-end/src/components/Engines/EngineCard.js
recruiter-front-end/src/components/Engines/EngineCardRules.js
recruiter-front-end/src/components/Engines/EngineDash.js
recruiter-front-end/src/components/Engines/NewEngine.js
recruiter-front-end/src/components/Login.js
recruiter-front-end/src/components/NewCandidate/NewCandidate.js
recruiter-front-end/src/index.js
recruiter-front-end/src/views/NewRulesPage/Education.js
recruiter-front-end/src/views/NewRulesPage/Experience.js
recruiter-front-end/src/views/NewRulesPage/Skills.js
recruiter-front-end/yarn.lock

Title. Cleaned up most of the stray console logs that are not needed anymore.

Login fixes, redirects, conventions, cleanup

---

recruiter-front-end/.vscode/settings.json
recruiter-front-end/package.json
recruiter-front-end/public/_redirects
recruiter-front-end/src/App.js
recruiter-front-end/src/actions/contactActions.js
recruiter-front-end/src/actions/emailActions.js
recruiter-front-end/src/actions/engineActions.js
recruiter-front-end/src/actions/groupActions.js
recruiter-front-end/src/actions/groupContactsActions.js
recruiter-front-end/src/actions/ruleActions.js
recruiter-front-end/src/actions/userActions.js
recruiter-front-end/src/components/Engines/AddRuleToEngine/AddRuleToEngine.js
recruiter-front-end/src/components/Engines/AddRuleToEngine/NewRuleConfirm.js
recruiter-front-end/src/components/Engines/AddRuleToEngine/NewRuleContact.js
recruiter-front-end/src/components/Engines/AddRuleToEngine/NewRuleEducation.js
recruiter-front-end/src/components/Engines/AddRuleToEngine/NewRuleExperience.js
recruiter-front-end/src/components/Engines/AddRuleToEngine/NewRuleSkills.js
recruiter-front-end/src/components/Engines/EngineCard.js
recruiter-front-end/src/components/Engines/EngineCardRules.js
recruiter-front-end/src/components/Engines/EngineDash.js
recruiter-front-end/src/components/Engines/NewEngine.js
recruiter-front-end/src/components/Login.js
recruiter-front-end/src/components/NewCandidate/NewCandidate.js
recruiter-front-end/src/index.js
recruiter-front-end/src/views/AddCandidatePage/CandidateConfirm.js
recruiter-front-end/src/views/NewRulesPage/Education.js
recruiter-front-end/src/views/NewRulesPage/Experience.js
recruiter-front-end/src/views/NewRulesPage/NewRuleContacts.js
recruiter-front-end/src/views/NewRulesPage/Skills.js
recruiter-front-end/yarn.lock

*** Please merge Omar's most recent PR before this one or we will get merge conflicts****
Everything in this checklist is required for each PR.  Please do not approve a PR that does not have all of these items.  
- [] I have made corresponding changes to the documentation
- [] I have added tests that prove my fix is effective or that my feature works

Fixes the styling on the new rules on existing engine flow and adds engine name above flow

---

recruiter-front-end/src/components/Engines/AddRuleToEngine/NewRuleConfirm.js

The back button on confirm was going to skills instead of experience where it should go. 

fixed broken link

---

recruiter-front-end/public/index.html

added tag manager to index.html
